# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "virtualbox" do |v|
    v.name = "vault-demo"
  end

  config.vm.box = "chef/centos-7.0"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.synced_folder "../data", "/vagrant_data"

  #require the vagrant-omnibus plugin: vagrant plugin install vagrant-omnibus
  config.omnibus.chef_version = :latest

  config.vm.provision "chef_solo" do |chef|
    # chef.data_bags_path = "../my-recipes/data_bags"
    chef.add_recipe "vault_demo"
    # chef.json = { mysql_password: "foo" }
  end
end
