---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2
  network:
    - ["forwarded_port", {guest: 8080, host: 18080}]
    - ["forwarded_port", {guest: 27017, host: 37017}]

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[vault_demo::default]
    attributes:
